# Generated by Django 4.2.2 on 2023-07-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeration',
            name='verification',
            field=models.BooleanField(default=False),
        ),
    ]
